# Game Constants
SCREEN_WIDTH, SCREEN_HEIGHT = 800,800
# Board Constants
BOARD_WIDTH,BOARD_HEIGHT = 800,800
BOARD_POSITION_X = 0
BOARD_POSITION_Y = 0
# 16 for Tiles, 16 for edges
ROWS = 16
COLS = 16
TILE_SIZE = BOARD_WIDTH//COLS
# Wall Constants
MARGIN = 5
