# Game Constatns
SCREEN_WIDTH, SCREEN_HEIGHT = 800,700
SCREEN_SIZE = (SCREEN_WIDTH,SCREEN_HEIGHT)

# Board Constants
BOARD_WIDTH,BOARD_HEIGHT = 600,600
ROWS,COLS = 16,16
SQUARE_SIZE = BOARD_WIDTH//COLS
MARGIN = 5

# Wall Constants
WALL_HEIGHT = MARGIN
WALL_WIDTH = MARGIN
